name: Deploy to mod.io

on:
  release:
    types: [published]
  workflow_dispatch:
        
env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
        
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}
      
    - name: MSBuild
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: powershell
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
    
    - name: Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: dotnet test --verbosity normal --settings coverlet.runsettings --logger:trx
    
    - name: Get Release Tag
      id: get_version
      run: echo "release_tag=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
        
    - name: Create ZIP
      id: filename
      run: |
        $tagName = "${{ env.release_tag }}"
        echo "${tagName}"
        $archiveName = "XLMenuMod-${tagName}.zip"
        echo "${archiveName}"
        Compress-Archive -Path XLMenuMod/bin/Release -DestinationPath $archiveName -CompressionLevel Optimal
        echo "archive_name=$archiveName" >> $GITHUB_ENV
    
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: ${{ env.archive_name }} application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    #- name: Create XLMenuMod.Utilities Nuget Package
      #run: dotnet pack XLMenuMod.Utilities/XLMenuMod.Utilities.csproj --include-source --include-symbols --no-build -p:PackageVersion=${{ github.event.release.tag_name }}
      
    - uses: nickelc/upload-to-modio@v1.0.1
      with:
        token: ${{ secrets.MODIO_TOKEN }}
        game: 629 # skaterxl
        mod: 135638 # xlmenumod
        path: modfile.zip
        version: ${{ steps.get_version.outputs.release_tag }}
        changelog: ${{ github.event.release.description_html }}
    

        
    # upload files to release
