name: Deploy to mod.io

on:
  release:
    types: [published]
  workflow_dispatch:
        
env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
        
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}
      
    - name: MSBuild
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: powershell
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Cache Build
      uses: actions/cache@v2
      env:
        cache-name: cache-xlmenumod
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.event.release.tag_name }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
      
  test:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Retrieve Build from Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: .
        key: ${{ runner.os }}-primes
    
    - name: Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: dotnet test --verbosity normal --settings coverlet.runsettings --logger:trx
      
  package:
    needs: test
    runs-on: windows-latest
    steps:
    - name: Get Release Tag
      id: release_tag
      run: echo "::set-output name=release_tag::${{ github.event.release.tag_name }}"
        
    #- name: Get Latest Tag
      #if: $ {{ steps.release_tag.outputs.release_tag == null }}
      #uses: WyriHaximus/github-action-get-previous-tag@v1
        
    - name: Determine Archive Name
      id: filename
      shell: powershell
      run: |
        $TAG_NAME=${{ steps.release_tag.outputs.release_tag }}
        $TAG_NAME_REPLACED=$TAG_NAME.Replace(".", "-")
        echo $TAG_NAME_REPLACED
        $ARCHIVE_NAME="XLMenuMod-$($TAG_NAME_REPLACED).zip"
        echo "::set-output name=archive_name::$ARCHIVE_NAME"
      
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.0
      with:
        filename: ${{ steps.filename.outputs.archive_name }}
        path: ${{env.GITHUB_WORKSPACE}}XLMenuMod/bin/Release
        
    - name: Create XLMenuMod.Utilities Nuget Package
      run: dotnet pack XLMenuMod.Utilities/XLMenuMod.Utilities.csproj --include-source --include-symbols --no-build -p:PackageVersion=${{ github.event.release.tag_name }}
  
  deploy:
    needs: package
    runs-on: windows-latest
    steps:
      
    - uses: nickelc/upload-to-modio@v1.0.1
      with:
        token: ${{ secrets.MODIO_TOKEN }}
        game: 629 # skaterxl
        mod: 135638 # xlmenumod
        path: modfile.zip
        version: ${{ github.event.release.tag_name }}
        changelog: ${{ github.event.release.description_html }}
        
    # upload files to release
